version: "3.7"

services:
  opt-service:
    # image: jfffe/indeed_optimizer_base_image:latest
    container_name: opt-service
    # network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    command:
      pipenv run python ./app/main.py
    # entrypoint:
      # tail -f /dev/null

    env_file: '../backend/.env'
    environment:
      - SOCKET_ENDPOINT_URL=0.0.0.0
      - WEBHOOK_PORT=5000

    volumes:
      - ./app:/indeed_optimizer/app
      # synch time with local time
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    networks:
      indeed-network:

networks:
  indeed-network:
    name: indeed-network



# origianl version: 
# Joachim Ferstl (ffe):

# version: "3.7"

# services:
#   flask_api:
#     build: .
#     ports:
#       - "5000:5000"
