export enum ServerRole {
    OWNER = 'OWNER',
    MERKLETREEGENERATOR = 'MERKLETREEGENERATOR',
    PRODUCER = 'PRODUCER',
    CONSUMER = 'CONSUMER',
    EVU = 'EVU',
    UBT = 'UBT',
    AUTH = 'AUTH'
}