version: '3.8'

x-quorum-def: &quorum-def
    #restart: 'on-failure'
    image: '${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:latest}'
    expose:
        - '21000'
        - '50400'
    healthcheck:
        test:
            [
                'CMD',
                'wget',
                '--spider',
                '--proxy',
                'off',
                'http://localhost:8545',
            ]
        interval: 4s
        timeout: 4s
        retries: 10
        start_period: 5s
    labels:
        com.quorum.consensus: raft
    entrypoint:
        - /bin/sh
        - -c
        - |
            DDIR=/qdata/dd
            mkdir -p $${DDIR}/keystore
            mkdir -p $${DDIR}/geth
            cp /3nodes/raft/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
            cp /3nodes/keys/key$${NODE_ID} $${DDIR}/keystore/
            cat /3nodes/permissioned-nodes.json | sed 's/^\(.*\)@.*\?\(.*\)raftport=5040\([0-9]\)\(.*\)$$/\1@172.16.239.1\3:21000?discport=0\&raftport=50400\4/g' > $${DDIR}/static-nodes.json
            cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
            cat $${DDIR}/static-nodes.json
            GENESIS_FILE="/3nodes/genesis.json"
            NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
            GETH_ARGS_raft="--raft --raftport 50400"
            geth --datadir $${DDIR} init $${GENESIS_FILE}
            geth \
              --allow-insecure-unlock \
              --identity node$${NODE_ID}-raft \
              --datadir $${DDIR} \
              --permissioned \
              --nodiscover \
              --verbosity 5 \
              --networkid $${NETWORK_ID} \
              --rpc \
              --rpccorsdomain "*" \
              --rpcvhosts "*" \
              --rpcaddr 0.0.0.0 \
              --rpcport 8545 \
              --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft \
              --port 21000 \
              --unlock 0 \
              --password /3nodes/passwords.txt \
              ${QUORUM_GETH_ARGS:-} $${GETH_ARGS_raft}



services:

    truffle-migrator:
        image: truffle-migrator-dev:1.0.0
        # tty: true
        # hostname: truffle-migrator
        build:
            context: .
            dockerfile: Dockerfile_migration
        volumes:
            - ./build:/usr/build
            - ./circuits:/usr/circuits
            - ./contracts:/usr/contracts
            - ./circom:/usr/circom
        # entrypoint: truffle
        # entrypoint: tail -f /dev/null
        # command: >
            # migrate
              # --network quorum
              # --reset
        entrypoint:
            - /bin/sh
            - -c
            - |
                #####################################################
                ######## Bootstrapping the Labeling Circuit  ########

                cd /usr/circuits/labeling && circom labeling.circom --r1cs --wasm --sym --c
                cd /usr/circuits/labeling/labeling_cpp && make

                # cd /usr/circuits/labeling && \
                  # snarkjs powersoftau new bn128 14 pot12_0000.ptau -v
                # cd /usr/circuits/labeling && \
                  # snarkjs powersoftau contribute pot12_0000.ptau pot12_0001.ptau --name="First contribution" --entropy="Hallo" -v

                # cd /usr/circuits/labeling && \
                  # snarkjs powersoftau prepare phase2 pot12_0001.ptau pot12_final.ptau -v
                export NODE_OPTIONS=--max_old_space_size=8096
                echo "Using PoT"
                cd /usr/circuits/labeling && \
                  snarkjs groth16 setup labeling.r1cs ../../powersOfTau28_hez_final_21.ptau labeling_0000.zkey
                echo "Contribution"
                cd /usr/circuits/labeling && \
                  snarkjs zkey contribute labeling_0000.zkey labeling_0001.zkey --name="1st Contributor Name" -v --entropy="Hallo"
                echo "Generating verkey"
                cd /usr/circuits/labeling && \
                  snarkjs zkey export verificationkey labeling_0001.zkey verification_key.json

                # cd /usr/circuits/labeling && \
                  # snarkjs groth16 prove labeling_0001.zkey ./labeling_js/witness.wtns proof.json public.json
                # cd /usr/circuits/labeling && \
                  # snarkjs groth16 verify verification_key.json public.json proof.json

                cd /usr/circuits/labeling && \
                  snarkjs zkey export solidityverifier labeling_0001.zkey verifier.sol
                cp /usr/circuits/labeling/verifier.sol /usr/contracts/LabelingVerifier.sol

                cd /usr && truffle migrate --network quorum --reset

                tail -f /dev/null

        depends_on:
            - quorum-node1
            - quorum-node2
            - quorum-node3
        networks:
            indeed-network:
            quorum-simple-net:
                ipv4_address: 172.16.239.10

    quorum-node1:
        <<: *quorum-def
        # hostname: quorum-node1
        # ports:
            # - '22000:8545'
            # - '23000:8546'
        volumes:
            # - vol1:/qdata
            - ./quorum-network:/3nodes:ro
            - ${dir_name}/docker_timezone:/etc/localtime:ro
        environment:
            - PRIVATE_CONFIG=ignore
            - NODE_ID=1
        networks:
            indeed-network:
            quorum-simple-net:
                ipv4_address: 172.16.239.11
    quorum-node2:
        <<: *quorum-def
        # hostname: quorum-node2
        # ports:
            # - '22001:8545'
            # - '23001:8546'
        volumes:
            # - vol2:/qdata
            - ./quorum-network:/3nodes:ro
            - ${dir_name}/docker_timezone:/etc/localtime:ro
        environment:
            - PRIVATE_CONFIG=ignore
            - NODE_ID=2
        networks:
            indeed-network:
            quorum-simple-net:
                ipv4_address: 172.16.239.12
    quorum-node3:
        <<: *quorum-def
        # hostname: quorum-node3
        # ports:
            # - '22002:8545'
            # - '23002:8546'
        volumes:
            # - vol3:/qdata
            - ./quorum-network:/3nodes:ro
            - ${dir_name}/docker_timezone:/etc/localtime:ro
        environment:
            - PRIVATE_CONFIG=ignore
            - NODE_ID=3
        networks:
            indeed-network:
            quorum-simple-net:
                ipv4_address: 172.16.239.13

networks:
    quorum-simple-net:
        name: quorum-simple-net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.239.0/24
    indeed-network:
        name: indeed-network

volumes:
    'vol1':
    'vol2':
    'vol3':
