FROM ubuntu:20.04

WORKDIR /usr

USER root


# Replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Update and install prerequisites 
RUN apt-get update > /dev/null \
  && apt-get upgrade -y > /dev/null
RUN apt-get install -y \
  curl \
  wget \
  git \
  gcc \
  build-essential \
  libssl-dev \
  nlohmann-json3-dev \
  libgmp-dev \
  nasm \
  > /dev/null


# Install CMAKE
# RUN cd /tmp \
  # && wget -q https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0.tar.gz \
  # && tar -zxvf cmake-3.20.0.tar.gz >/dev/null \
  # && cd cmake-3.20.0 \
  # && ./bootstrap > /dev/null \
  # && make > /dev/null \
  # && make install > /dev/null


# Install RUST (Cargo)
RUN curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y > /dev/null
# RUN . /root/.cargo/env
ENV PATH=$PATH:/root/.cargo/bin
RUN echo $(cargo --version)

# Install CIRCOM
RUN git clone https://github.com/iden3/circom.git \
  && cd circom \
  && cargo build --release > /dev/null \
  && cargo install --path circom > /dev/null


# Declare constants
ENV NVM_VERSION v0.39.0
ENV NODE_VERSION v13.12.0

# Install NVM
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/${NVM_VERSION}/install.sh | bash

# Install NODE
RUN source ~/.nvm/nvm.sh; \
    nvm install $NODE_VERSION; \
    nvm use --delete-prefix $NODE_VERSION;

ENV PATH=$PATH:/root/.nvm/versions/node/${NODE_VERSION}/bin
RUN echo $(node -v)
RUN echo $(npm -v)

# Adding package.json and installing remaining node packages
ADD ./package.json  ./package.json
RUN npm i

# Install SNARKJS
RUN npm i snarkjs -g


# Adding contract and truffle config stuff
ADD circomlib ./circom/circomlib
ADD contracts ./contracts
ADD migrations ./migrations
ADD truffle-config.js .


#  Adding .env
ADD .env .

#  Installing truffle globally
RUN npm i --allow-root --unsafe-perm=true truffle@5.1.39 -g



# Adding .env
ADD .env .

# Getting powers of tau
RUN cd /usr && wget -q https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_21.ptau


CMD tail -f /dev/null
